### ISSUE TITLE
Function attributes not considering empty string as input

### ISSUE THREAD

**Issue by kumar550** [deep-compute/kwikapi#53] opened 2018-06-10 16:19 UTC
**Readme:**
- @RamanjaneyuluIdavalapati  I created an API(using `kwikapi`), when i am sending `empty` string as input, it fails to respond.

**codebase**
```python
import tornado.ioloop
import tornado.web

from kwikapi.tornado import RequestHandler
from kwikapi import API

# Core logic that you want to expose as a service
class Calc(object):
    def add(self, a: str, b: str) -> int:
        return a + b

# Standard boilerplate code to define the service. This
# code will remain more or less the same size regardless
# of how big the code/complexity of `BaseCalc` above is.

# Register BaseCalc with KwikAPI
api = API()
api.register(Calc(), 'v1')

# Passing RequestHandler to the KwikAPI
def make_app():
    return tornado.web.Application([
        (r'^/api/.*', RequestHandler, dict(api=api)),
    ])

# Starting the application
if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
```

**Comment by IdavalapatiRamanjaneyulu** [comment] 2018-06-11 05:10
@kumar550 
- I can able to reproduce the bug. The problem is with GET Request. The urllib parse is excluding the empty arguments.
- I will fix it in some time.
- In the mean time for quick usage can you please go with POST Request.
Eg:
```
url = 'http://localhost:8888/api/v1/add'
params = {'a': 'kumar', 'b': ''}
resp = requests.post(url, data=json.dumps(params))
```

**Comment by kumar550** [comment] 2018-06-11 06:25
Thank you @RamanjaneyuluIdavalapati 

For now, I will go with `POST` request.

**Comment by jaswanth098** [comment] 2019-05-07 10:00
As we are not working on kwikapi moving this to ready

**Closed as completed** 2022-10-19 13:55 UTC
Labels: bug-type, ready-status, meta-team, moveto-inprogress-3m
